
/**
 * Property Schema
 */

// TODO type placeholders temp
var Enum = String;
var Integer = Number;

/**
 * Schema export
 */

module.exports = {
  ListingId: {type:String, primary:true},
  ListingKey:{type:String, maxLength:255},
  ListAOR:   {type:String, maxLength:50},

  OriginatingSystemKey: {type:String, maxLength:255},
  OriginatingSystemName: {type:String, maxLength:255},
  ListingService: {type:String, maxLength:25},
  ListingAgreement: {type:String, maxLength:25},
  LeaseConsideredYN: {type:Boolean},
  HomeWarrantyYN: {type:Boolean},
  CopyrightNotice: {type:String, maxLength:500},
  Disclaimer: {type:String, maxLength:500},
  StandardStatus: {type:String, maxLength:25},
  MlsStatus: {type:String, maxLength:50},
  ApprovalStatus: {type:String, maxLength:25},

  PropertyType:    {type:Enum},
  PropertySubType: {type:Enum},

  ListingContractDate: {type:Date},
  ContractStatusChangeDate: {type:Date},
  ExpirationDate: {type:Date},
  CancelationDate: {type:Date},
  ContingentDate: {type:Date},
  WithdrawnDate: {type:Date},
  PurchaseContractDate: {type:Date},
  CloseDate: {type:Date},
  OnMarketDate:  {type:Date},
  OffMarketDate: {type:Date},

  PendingTimestamp: {type:Date},
  ModificationTimestamp: {type:Date},
  StatusChangeTimestamp: {type:Date},
  PriceChangeTimestamp: {type:Date},
  MajorChangeType: {type:String, maxLength:255},
  MajorChangeTimestamp: {type:Date},
  OriginalEntryTimestamp: {type:Date},
  OnMarketTimestamp: {type:Date},
  OffMarketTimestamp: {type:Date},

  DaysOnMarket: {type:Integer},
  CumulativeDaysOnMarket: {type:Integer},

  ClosePrice: {type:Number},
  ListPrice: {type:Number, required:true},
  OriginalListPrice: {type:Number},
  ListPriceLow: {type:Number},
  PreviousListPrice: {type:Number},

  BuyerAgencyCompensation: {type:String, maxLength:25},
  BuyerAgencyCompensationType: {type:String, maxLength:25},
  SubAgencyCompensation: {type:String, maxLength:25},
  SubAgencyCompensationType: {type:String, maxLength:25},
  TransactionBrokerCompensation: {type:String, maxLength:25},
  TransactionBrokerCompensationType: {type:String, maxLength:25},
  DualVariableCompensationYN: {type:Boolean},
  LeaseRenewalCompensation: {type:String, maxLength:255},

  VOWEntireListingDisplayYN: {type:Boolean},
  VOWAddressDisplayYN: {type:Boolean},
  VOWConsumerCommentYN: {type:Boolean},
  VOWAutomatedValuationDisplayYN: {type:Boolean},
  SignOnPropertyYN: {type:Boolean},
  IDXEntireListingDisplayYN: {type:Boolean},
  IDXAddressDisplayYN: {type:Boolean},
  IDXConsumerCommentYN: {type:Boolean},
  IDXAutomatedValuationDisplayYN: {type:Boolean},
  PhotosCount: {type:Integer, default:0},
  PhotosChangeTimestamp: {type:Date},
  VideosCount: {type:Integer},
  VideosChangeTimestamp: {type:Date},
  DocumentsCount: {type:Integer},
  DocumentsChangeTimestamp: {type:Date},
  DocumentsAvailable: {type:String, maxLength:1024},
  VirtualTourURLUnbranded: {type:String, maxLength:8000},
  VirtualTourURLBranded: {type:String, maxLength:8000},
  PublicRemarks: {type:String, maxLength:4000},
  PrivateRemarks: {type:String, maxLength:4000},
  PrivateOfficeRemarks: {type:String, maxLength:4000},
  ShowingInstructions: {type:String, maxLength:4000},
  ShowingContactPhoneNumber: {type:String, maxLength:16},
  ShowingContactPhoneExtension: {type:Integer},
  ShowingContactName: {type:String, maxLength:40},
  ShowingContactType: {type:String, maxLength:75},
  LockBoxLocation: {type:String, maxLength:255},
  LockBoxType: {type:String, maxLength:255},
  LockBoxSerialNumber: {type:String, maxLength:25},
  Exclusions: {type:String, maxLength:1024},
  Inclusions: {type:String, maxLength:1024},
  Disclosures: {type:String, maxLength:4000},
  Ownership: {type:String, maxLength:1024},
  SpecialListingConditions: {type:String, maxLength:1024},
  ListingTerms: {type:String, maxLength:1024},
  ListingFinancing: {type:String, maxLength:1024},
  BuyerFinancing: {type:String, maxLength:1024},
  Contingency: {type:String, maxLength:1024},
  Possession: {type:String, maxLength:255},
  ClosingTerms: {type:String, maxLength:1024},

  StreetNumber: {type:String, required:true, maxLength:25},
  StreetNumberNumeric: {type:Integer},
  StreetDirPrefix: {type:String, maxLength:15},
  StreetName: {type:String, required:true, maxLength:50},
  StreetAdditionalInfo: {type:String, maxLength:50},
  StreetSuffix: {type:String, maxLength:25},
  StreetSuffixModifier: {type:String, maxLength:25},
  StreetDirSuffix: {type:String, maxLength:15},
  UnitNumber: {type:String, maxLength:25},
  City: {type:String, required:true, maxLength:50},
  StateOrProvince: {type:String, required:true, maxLength:2},
  Country: {type:String, maxLength:2, default:'USA'},
  PostalCode: {type:String, required:true, maxLength:10},
  PostalCodePlus4: {type:String, maxLength:4},
  CarrierRoute: {type:String, maxLength:9},
  UnparsedAddress: {type:String, maxLength:255},
  PostalCity: {type:String, maxLength:50},
  CountyOrParish: {type:String, maxLength:50},
  Township: {type:String, maxLength:50},

  MLSAreaMajor: {type:String, maxLength:50},
  MLSAreaMinor: {type:String, maxLength:50},
  SubdivisionName: {type:String, maxLength:50},
  Latitude: {type:Number},
  Longitude: {type:Number},
  Directions: {type:String, maxLength:1024},
  MapCoordinate: {type:String, maxLength:25},
  MapCoordinateSource: {type:String, maxLength:25},
  MapURL: {type:String, maxLength:8000},

  CrossStreet: {type:String, maxLength:50},
  ElementarySchool: {type:String, maxLength:50},
  ElementarySchoolDistrict: {type:String, maxLength:50},
  MiddleOrJuniorSchool: {type:String, maxLength:50},
  MiddleOrJuniorSchoolDistrict: {type:String, maxLength:50},
  HighSchool: {type:String, maxLength:50},
  HighSchoolDistrict: {type:String, maxLength:50},
  ListAgentNamePrefix: {type:String, maxLength:10},
  ListAgentFirstName: {type:String, required:true, maxLength:50},
  ListAgentMiddleName: {type:String, maxLength:50},
  ListAgentLastName: {type:String, required:true, maxLength:50},
  ListAgentNameSuffix: {type:String, maxLength:10},
  ListAgentFullName: {type:String, maxLength:150},
  ListAgentPreferredPhone: {type:String, maxLength:16},
  ListAgentPreferredPhoneExt: {type:Integer},
  ListAgentOfficePhone: {type:String, maxLength:16},
  ListAgentOfficePhoneExt: {type:Integer},
  ListAgentCellPhone: {type:String, maxLength:16},
  ListAgentDirectPhone: {type:String, maxLength:16},
  ListAgentHomePhone: {type:String, maxLength:16},
  ListAgentFax: {type:String, maxLength:16},
  ListAgentPager: {type:String, maxLength:16},
  ListAgentVoiceMail: {type:String, maxLength:16},
  ListAgentVoiceMailExt: {type:Integer},
  ListAgentTollFreePhone: {type:String, maxLength:16},
  ListAgentEmail: {type:String, required:true, maxLength:80},
  ListAgentURL: {type:String, maxLength:8000},
  ListAgentKey: {type:String, maxLength:255},
  ListAgentAOR: {type:String, maxLength:50},
  ListAgentMlsId: {type:String, maxLength:25},
  ListAgentStateLicense: {type:String, maxLength:50},
  ListAgentDesignation: {type:String, maxLength:50},
  ListOfficeName: {type:String, required:true, maxLength:50},
  ListOfficePhone: {type:String, maxLength:16},
  ListOfficePhoneExt: {type:Integer},
  ListOfficeFax: {type:String, maxLength:16},
  ListOfficeEmail: {type:String, maxLength:80},
  ListOfficeURL: {type:String, maxLength:8000},
  ListOfficeKey: {type:String, maxLength:255},
  ListOfficeAOR: {type:String, maxLength:50},
  ListOfficeMlsId: {type:String, maxLength:25},
  CoListAgentNamePrefix: {type:String, maxLength:10},
  CoListAgentFirstName: {type:String, maxLength:50},
  CoListAgentMiddleName: {type:String, maxLength:50},
  CoListAgentLastName: {type:String, maxLength:50},
  CoListAgentNameSuffix: {type:String, maxLength:10},
  CoListAgentFullName: {type:String, maxLength:150},
  CoListAgentPreferredPhone: {type:String, maxLength:16},
  CoListAgentPreferredPhoneExt: {type:Integer},
  CoListAgentOfficePhone: {type:String, maxLength:16},
  CoListAgentOfficePhoneExt: {type:Integer},
  CoListAgentCellPhone: {type:String, maxLength:16},
  CoListAgentDirectPhone: {type:String, maxLength:16},
  CoListAgentHomePhone: {type:String, maxLength:16},
  CoListAgentFax: {type:String, maxLength:16},
  CoListAgentPager: {type:String, maxLength:16},
  CoListAgentVoiceMail: {type:String, maxLength:16},
  CoListAgentVoiceMailExt: {type:Integer},
  CoListAgentTollFreePhone: {type:String, maxLength:16},
  CoListAgentEmail: {type:String, maxLength:80},
  CoListAgentURL: {type:String, maxLength:8000},
  CoListAgentKey: {type:String, maxLength:255},
  CoListAgentAOR: {type:String, maxLength:50},
  CoListAgentMlsId: {type:String, maxLength:25},
  CoListAgentStateLicense: {type:String, maxLength:50},
  CoListAgentDesignation: {type:String, maxLength:50},
  CoListOfficeName: {type:String, maxLength:50},
  CoListOfficePhone: {type:String, maxLength:16},
  CoListOfficePhoneExt: {type:Integer},
  CoListOfficeFax: {type:String, maxLength:16},
  CoListOfficeEmail: {type:String, maxLength:80},
  CoListOfficeURL: {type:String, maxLength:8000},
  CoListOfficeKey: {type:String, maxLength:255},
  CoListOfficeAOR: {type:String, maxLength:50},
  CoListOfficeMlsId: {type:String, maxLength:25},
  BuyerAgentNamePrefix: {type:String, maxLength:10},
  BuyerAgentFirstName: {type:String, maxLength:50},
  BuyerAgentMiddleName: {type:String, maxLength:50},
  BuyerAgentLastName: {type:String, maxLength:50},
  BuyerAgentNameSuffix: {type:String, maxLength:10},
  BuyerAgentFullName: {type:String, maxLength:150},
  BuyerAgentPreferredPhone: {type:String, maxLength:16},
  BuyerAgentPreferredPhoneExt: {type:Integer},
  BuyerAgentOfficePhone: {type:String, maxLength:16},
  BuyerAgentOfficePhoneExt: {type:Integer},
  BuyerAgentCellPhone: {type:String, maxLength:16},
  BuyerAgentDirectPhone: {type:String, maxLength:16},
  BuyerAgentHomePhone: {type:String, maxLength:16},
  BuyerAgentFax: {type:String, maxLength:16},
  BuyerAgentPager: {type:String, maxLength:16},
  BuyerAgentVoiceMail: {type:String, maxLength:16},
  BuyerAgentVoiceMailExt: {type:Integer},
  BuyerAgentTollFreePhone: {type:String, maxLength:16},
  BuyerAgentEmail: {type:String, maxLength:80},
  BuyerAgentURL: {type:String, maxLength:8000},
  BuyerAgentKey: {type:String, maxLength:255},
  BuyerAgentAOR: {type:String, maxLength:50},
  BuyerAgentMlsId: {type:String, maxLength:25},
  BuyerAgentStateLicense: {type:String, maxLength:50},
  BuyerAgentDesignation: {type:String, maxLength:50},
  BuyerOfficeName: {type:String, maxLength:50},
  BuyerOfficePhone: {type:String, maxLength:16},
  BuyerOfficePhoneExt: {type:Integer},
  BuyerOfficeFax: {type:String, maxLength:16},
  BuyerOfficeEmail: {type:String, maxLength:80},
  BuyerOfficeURL: {type:String, maxLength:8000},
  BuyerOfficeKey: {type:String, maxLength:255},
  BuyerOfficeAOR: {type:String, maxLength:50},
  BuyerOfficeMlsId: {type:String, maxLength:25},
  CoBuyerAgentNamePrefix: {type:String, maxLength:10},
  CoBuyerAgentFirstName: {type:String, maxLength:50},
  CoBuyerAgentMiddleName: {type:String, maxLength:50},
  CoBuyerAgentLastName: {type:String, maxLength:50},
  CoBuyerAgentNameSuffix: {type:String, maxLength:10},
  CoBuyerAgentFullName: {type:String, maxLength:150},
  CoBuyerAgentPreferredPhone: {type:String, maxLength:16},
  CoBuyerAgentPreferredPhoneExt: {type:Integer},
  CoBuyerAgentOfficePhone: {type:String, maxLength:16},
  CoBuyerAgentOfficePhoneExt: {type:Integer},
  CoBuyerAgentCellPhone: {type:String, maxLength:16},
  CoBuyerAgentDirectPhone: {type:String, maxLength:16},
  CoBuyerAgentHomePhone: {type:String, maxLength:16},
  CoBuyerAgentFax: {type:String, maxLength:16},
  CoBuyerAgentPager: {type:String, maxLength:16},
  CoBuyerAgentVoiceMail: {type:String, maxLength:16},
  CoBuyerAgentVoiceMailExt: {type:Integer},
  CoBuyerAgentTollFreePhone: {type:String, maxLength:16},
  CoBuyerAgentEmail: {type:String, maxLength:80},
  CoBuyerAgentURL: {type:String, maxLength:8000},
  CoBuyerAgentKey: {type:String, maxLength:255},
  CoBuyerAgentAOR: {type:String, maxLength:50},
  CoBuyerAgentMlsId: {type:String, maxLength:25},
  CoBuyerAgentStateLicense: {type:String, maxLength:50},
  CoBuyerAgentDesignation: {type:String, maxLength:50},
  CoBuyerOfficeName: {type:String, maxLength:50},
  CoBuyerOfficePhone: {type:String, maxLength:16},
  CoBuyerOfficePhoneExt: {type:Integer},
  CoBuyerOfficeFax: {type:String, maxLength:16},
  CoBuyerOfficeEmail: {type:String, maxLength:80},
  CoBuyerOfficeURL: {type:String, maxLength:8000},
  CoBuyerOfficeKey: {type:String, maxLength:255},
  CoBuyerOfficeAOR: {type:String, maxLength:50},
  CoBuyerOfficeMlsId: {type:String, maxLength:25},
  ListTeamDisplayName: {type:String, maxLength:50},
  BuyerTeamDisplayName: {type:String, maxLength:50},
  AssociationYN: {type:Boolean},
  AssociationName: {type:String, maxLength:50},
  AssociationPhone: {type:String, maxLength:16},
  AssociationFee: {type:Number},
  AssociationFeeFrequency: {type:String, maxLength:25},
  AssociationName2: {type:String, maxLength:50},
  AssociationPhone2: {type:String, maxLength:16},
  AssociationFee2: {type:Number},
  AssociationFee2Frequency: {type:String, maxLength:25},
  AssociationFeeIncludes: {type:String, maxLength:1024},
  AssociationAmenities: {type:String, maxLength:1024},
  LotSizeArea: {type:Number},
  LotSizeSource: {type:String, maxLength:50},
  LotSizeUnits: {type:String, maxLength:25},
  LotSizeDimensions: {type:String, maxLength:150},
  LotDimensionsSource: {type:String, maxLength:50},
  LotSizeAcres: {type:Number},
  LotSizeSquareFeet: {type:Number},
  FrontageType: {type:String, maxLength:50},
  FrontageLength: {type:String, maxLength:255},
  RoadFrontageType: {type:String, maxLength:255},
  RoadSurfaceType: {type:String, maxLength:255},
  RoadResponsibility: {type:String, maxLength:50},
  OccupantName: {type:String, maxLength:50},
  OccupantPhone: {type:String, maxLength:16},
  OccupantType: {type:String, maxLength:50},
  OwnerName: {type:String, maxLength:50},
  OwnerPhone: {type:String, maxLength:16},
  LeaseTerm: {type:String, maxLength:25},
  LandLeaseYN: {type:Boolean},
  LandLeaseAmount: {type:Number},
  LandLeaseAmountFrequency: {type:String, maxLength:25},
  LandLeaseExpirationDate: {type:Date},
  View: {type:String, maxLength:1024},
  ViewYN: {type:Boolean},
  LotFeatures: {type:String, maxLength:1024},
  CurrentUse: {type:String, maxLength:1024},
  PossibleUse: {type:String, maxLength:1024},
  DevelopmentStatus: {type:String, maxLength:1024},
  NumberofLots: {type:Integer},
  HorseYN: {type:Boolean},
  HorseAmenities: {type:String, maxLength:1024},
  CommunityFeatures: {type:String, maxLength:1024},
  SeniorCommunityYN: {type:Boolean},
  PoolFeatures: {type:String, maxLength:1024},
  PoolPrivateYN: {type:Boolean},
  SpaFeatures: {type:String, maxLength:1024},
  SpaYN: {type:Boolean},
  WaterfrontYN: {type:Boolean},
  WaterBodyName: {type:String, maxLength:50},
  GrossScheduledIncome: {type:Number},
  IncomeIncludes: {type:String, maxLength:1024},
  OperatingExpense: {type:Number},
  OperatingExpenseIncludes: {type:String, maxLength:1024},
  NetOperatingIncome: {type:Number},
  CapRate: {type:Number},
  NumberOfUnitsLeased: {type:Integer},
  NumberOfUnitsMoMo: {type:Integer},
  NumberOfUnitsVacant: {type:Integer},
  ExistingLeaseType: {type:String, maxLength:75},
  UnitsFurnished: {type:String, maxLength:25},
  TotalActualRent: {type:Number},
  RentControlYN: {type:Boolean},
  NumberOfUnitsTotal: {type:Integer},
  NumberOfUnitsBuildings: {type:Integer},
  TenantPays: {type:String, maxLength:255},
  OwnerPays: {type:String, maxLength:255},
  VacancyAllowance: {type:Integer},
  CableTvExpense: {type:Number},
  ElectricExpense: {type:Number},
  GardnerExpense: {type:Number},
  FurnitureReplacementExpense: {type:Number},
  GasExpense: {type:Number},
  InsuranceExpense: {type:Number},
  OtherExpense: {type:Number},
  LicensesExpense: {type:Number},
  MaintenanceExpense: {type:Number},
  NewTaxesExpense: {type:Number},
  PestControlExpense: {type:Number},
  PoolExpense: {type:Number},
  SuppliesExpense: {type:Number},
  TrashExpense: {type:Number},
  WaterSewerExpense: {type:Number},
  WorkmansCompensationExpense: {type:Number},
  ProfessionalManagementExpense: {type:Number},
  ManagerExpense: {type:Number},
  FinancialDataSource: {type:String, maxLength:75},
  RentIncludes: {type:String, maxLength:255},
  Utilities: {type:String, maxLength:1024},
  Electric: {type:String, maxLength:255},
  Gas: {type:String, maxLength:255},
  Telephone: {type:String, maxLength:255},
  IrrigationWaterRightsYN: {type:Boolean},
  IrrigationWaterRightsAcres: {type:Integer},
  IrrigationSource: {type:String, maxLength:255},
  WaterSource: {type:String, maxLength:1024},
  DistanceToWater: {type:String, maxLength:255},
  ElectricOnPropertyYN: {type:String, maxLength:1},
  DistanceToElectric: {type:String, maxLength:255},
  Sewer: {type:String, maxLength:1024},
  DistanceToSewer: {type:String, maxLength:255},
  DistanceToGas: {type:String, maxLength:255},
  DistanceToPhoneService: {type:String, maxLength:255},
  DistanceToStreet: {type:String, maxLength:255},
  DistanceToSchools: {type:String, maxLength:255},
  DistanceFromShopping: {type:String, maxLength:255},
  DistanceToPlaceofWorship: {type:String, maxLength:255},
  DistanceToBus: {type:String, maxLength:255},
  DistanceToFreeway: {type:String, maxLength:255},
  CropsIncludedYN: {type:Boolean},
  GrazingPermitsBlmYN: {type:Boolean},
  GrazingPermitsForestServiceYN: {type:Boolean},
  GrazingPermitsPrivateYN: {type:Boolean},
  CultivatedArea: {type:Number},
  PastureArea: {type:Number},
  RangeArea: {type:Number},
  WoodedArea: {type:Number},
  Vegetation: {type:String, maxLength:1024},
  Fencing: {type:String, maxLength:255},
  DistanceFromSchoolBus: {type:String, maxLength:255},
  FarmCreditServiceInclYN: {type:Boolean},
  FarmLandAreaUnits: {type:String, maxLength:25},
  FarmLandAreaSource: {type:String, maxLength:50},
  BedroomsTotal: {type:Integer, default:0},
  BedroomsPossible: {type:Integer},
  BathroomsTotal: {type:String, default:0, maxLength:25},
  BathroomsFull: {type:Integer},
  BathroomsHalf: {type:Integer},
  BathroomsThreeQuarter: {type:Integer},
  BathroomsOneQuarter: {type:Integer},
  LivingArea: {type:Number, required:true},
  LivingAreaSource: {type:String, maxLength:50},
  LivingAreaUnits: {type:String, maxLength:25},
  AboveGradeFinishedArea: {type:Number},
  AboveGradeFinishedAreaSource: {type:String, maxLength:50},
  AboveGradeFinishedAreaUnits: {type:String, maxLength:25},
  BelowGradeFinishedArea: {type:Number},
  BelowGradeFinishedAreaSource: {type:String, maxLength:50},
  BelowGradeFinishedAreaUnits: {type:String, maxLength:25},
  BuildingAreaTotal: {type:Number},
  BuildingAreaSource: {type:String, maxLength:50},
  BuildingAreaUnits: {type:String, maxLength:25},
  CommonWalls: {type:String, maxLength:1024},
  PropertyAttachedYN: {type:Boolean},
  FoundationArea: {type:Number},
  GarageYN: {type:Boolean},
  GarageSpaces: {type:Number},
  AttachedGarageYN: {type:Boolean},
  CarportSpaces: {type:Number},
  CarportYN: {type:Boolean},
  OpenParkingYN: {type:Boolean},
  OpenParkingSpaces: {type:Number},
  CoveredSpaces: {type:Number},
  ParkingFeatures: {type:String, maxLength:1024},
  OtherParking: {type:String, maxLength:1024},
  ParkingTotal: {type:Number},
  RVParkingDimensions: {type:String, maxLength:50},
  StoriesTotal: {type:Integer},
  Stories: {type:Integer},
  Levels: {type:String, maxLength:1024},
  EntryLocation: {type:String, maxLength:50},
  EntryLevel: {type:Integer},
  YearBuilt: {type:Integer},
  YearBuiltEffective: {type:Integer},
  YearBuiltDetails: {type:String, maxLength:1024},
  YearBuiltSource: {type:String, maxLength:60},
  NewConstructionYN: {type:Boolean},
  GreenBuildingVerification: {type:String, maxLength:1024},
/* collection */
  Green: {type:"array", elementType:"reso.Green"},
/* collection */
  BuilderName: {type:String, maxLength:50},
  BuilderModel: {type:String, maxLength:50},
  Heating: {type:String, maxLength:1024},
  HeatingYN: {type:Boolean},
  Cooling: {type:String, maxLength:1024},
  CoolingYN: {type:Boolean},
  InteriorFeatures: {type:String, maxLength:1024},
  ExteriorFeatures: {type:String, maxLength:1024},
  PatioAndPorchFeatures: {type:String, maxLength:1024},
  ArchitecturalStyle: {type:String, maxLength:1024},
  FireplaceFeatures: {type:String, maxLength:1024},
  FireplacesTotal: {type:Integer, default:0},
  FireplaceYN: {type:Boolean},
  DoorFeatures: {type:String, maxLength:1024},
  WindowFeatures: {type:String, maxLength:1024},
  Roof: {type:String, maxLength:1024},
  ConstructionMaterials: {type:String, maxLength:1024},
  FoundationDetails: {type:String, maxLength:1024},
  Basement: {type:String, maxLength:1024},
  Flooring: {type:String, maxLength:1024},
  OtherStructures: {type:String, maxLength:1024},
  DirectionFaces: {type:String, maxLength:25},
  OtherEquipment: {type:String, maxLength:1024},
  Appliances: {type:String, maxLength:1024},
  LaundryFeatures: {type:String, maxLength:1024},
  SecurityFeatures: {type:String, maxLength:1024},
  NumberOfSeparateElectricMeters: {type:Integer},
  NumberOfSeparateGasMeters: {type:Integer},
  NumberOfSeparateWaterMeters: {type:Integer},
  GreenEnergyEfficient: {type:String, maxLength:1024},
  GreenEnergyGeneration: {type:String, maxLength:1024},
  GreenSustainability: {type:String, maxLength:1024},
  GreenWaterConservation: {type:String, maxLength:1024},
  GreenIndoorAirQuality: {type:String, maxLength:1024},
  GreenLocation: {type:String, maxLength:1024},
  WalkScore: {type:Integer},
  HabitableResidenceYN: {type:Boolean},
  MobileLength: {type:Integer},
  MobileWidth: {type:Integer},
  BodyType: {type:String, maxLength:1024},
  Skirt: {type:String, maxLength:1024},
  MobileDimUnits: {type:String, maxLength:25},
  ParkName: {type:String, maxLength:50},
  ParkManagerName: {type:String, maxLength:50},
  ParkManagerPhone: {type:String, maxLength:16},
  MobileHomeRemainsYN: {type:Boolean},
  Make: {type:String, maxLength:50},
  Model: {type:String, maxLength:50},
  NumberOfPads: {type:Integer},
  SerialU: {type:String, maxLength:25},
  DOH1: {type:String, maxLength:25},
  License1: {type:String, maxLength:25},
  SerialX: {type:String, maxLength:25},
  DOH2: {type:String, maxLength:25},
  License2: {type:String, maxLength:25},
  SerialXX: {type:String, maxLength:25},
  DOH3: {type:String, maxLength:25},
  License3: {type:String, maxLength:25},
  AccessibilityFeatures: {type:String, maxLength:1024},
  RoomsTotal: {type:Integer},
  RoomType: {type:String, maxLength:1024},
/* collection */
  Room: {type:"array", elementType:"reso.Room"},
/* collection */
/* collection */
  UnitType: {type:"array", elementType:"reso.UnitType"},
/* collection */
  Zoning: {type:String, maxLength:25},
  ZoningDescription: {type:String, maxLength:255},
  ParcelNumber: {type:String, maxLength:50},
  AdditionalParcelsYN: {type:Boolean},
  AdditionalParcelsDescription: {type:String, maxLength:255},
  TaxLot: {type:String, maxLength:25},
  TaxBlock: {type:String, maxLength:25},
  TaxTract: {type:String, maxLength:25},
  TaxLegalDescription: {type:String, maxLength:6000},
  TaxAmount: {type:Integer},
  TaxAmountFrequency: {type:String, maxLength:25},
  TaxYear: {type:Integer},
  TaxAssessedValue: {type:Integer},
  TaxExemptions: {type:String, maxLength:1024},
  TaxOtherAssessmentAmount: {type:Integer},
  TaxOtherAssessmentAmountFrequency: {type:String, maxLength:25},
  TaxBookNumber: {type:String, maxLength:25},
  TaxMapNumber: {type:String, maxLength:25},
  TaxParcelLetter: {type:String, maxLength:25},
  TaxStatusCurrent: {type:String, maxLength:50},
  PublicSurveySection: {type:String, maxLength:20},
  PublicSurveyTownship: {type:String, maxLength:20},
  PublicSurveyRange: {type:String, maxLength:20},

  /* non-standard fields */

  Photos:{type:Array, default:[]},
  Coordinates:{type:Object}
};
