
/**
 * Property Schema
 */

// TODO type placeholders temp
var Enum = String;
var Integer = Number;

/**
 * Schema export
 */

module.exports = {
  ListingId: {type:String, primary:true, group:'/Listing'},
  ListingKey:{type:String, maxLength:255, group:'/Listing'},
  ListAOR:   {type:String, maxLength:50, group:'/Listing'},

  OriginatingSystemKey: {type:String, maxLength:255, group:'/Listing'},
  OriginatingSystemName: {type:String, maxLength:255, group:'/Listing'},
  ListingService: {type:String, maxLength:25, group:'/Listing'},
  ListingAgreement: {type:String, maxLength:25, group:'/Listing'},
  LeaseConsideredYN: {type:Boolean, group:'/Listing'},
  HomeWarrantyYN: {type:Boolean, group:'/Listing'},
  CopyrightNotice: {type:String, maxLength:500, group:'/Listing'},
  Disclaimer: {type:String, maxLength:500, group:'/Listing'},
  StandardStatus: {type:String, maxLength:25, group:'/Listing'},
  MlsStatus: {type:String, maxLength:50, group:'/Listing'},
  ApprovalStatus: {type:String, maxLength:25, group:'/Listing'},

  PropertyType:    {type:Enum, group:'/Listing'},
  PropertySubType: {type:Enum, group:'/Listing'},

  ListingContractDate: {type:Date, group:'/Listing/Dates'},
  ContractStatusChangeDate: {type:Date, group:'/Listing/Dates'},
  ExpirationDate: {type:Date, group:'/Listing/Dates'},
  CancelationDate: {type:Date, group:'/Listing/Dates'},
  ContingentDate: {type:Date, group:'/Listing/Dates'},
  WithdrawnDate: {type:Date, group:'/Listing/Dates'},
  PurchaseContractDate: {type:Date, group:'/Listing/Dates'},
  CloseDate: {type:Date, group:'/Listing/Dates'},
  OnMarketDate:  {type:Date, group:'/Listing/Dates'},
  OffMarketDate: {type:Date, group:'/Listing/Dates'},

  PendingTimestamp: {type:Date, group:'/Listing/Dates'},
  ModificationTimestamp: {type:Date, group:'/Listing/Dates'},
  StatusChangeTimestamp: {type:Date, group:'/Listing/Dates'},
  PriceChangeTimestamp: {type:Date, group:'/Listing/Dates'},
  MajorChangeType: {type:String, maxLength:255, group:'/Listing/Dates'},
  MajorChangeTimestamp: {type:Date, group:'/Listing/Dates'},
  OriginalEntryTimestamp: {type:Date, group:'/Listing/Dates'},
  OnMarketTimestamp: {type:Date, group:'/Listing/Dates'},
  OffMarketTimestamp: {type:Date, group:'/Listing/Dates'},

  DaysOnMarket: {type:Integer, group:'/Listing/Dates'},
  CumulativeDaysOnMarket: {type:Integer, group:'/Listing/Dates'},

  ClosePrice: {type:Number, group:'/Listing/Price'},
  ListPrice: {type:Number, required:true, group:'/Listing/Price'},
  OriginalListPrice: {type:Number, group:'/Listing/Price'},
  ListPriceLow: {type:Number, group:'/Listing/Price'},
  PreviousListPrice: {type:Number, group:'/Listing/Price'},

  BuyerAgencyCompensation: {type:String, maxLength:25, group:'/Listing/Compensation'},
  BuyerAgencyCompensationType: {type:String, maxLength:25, group:'/Listing/Compensation'},
  SubAgencyCompensation: {type:String, maxLength:25, group:'/Listing/Compensation'},
  SubAgencyCompensationType: {type:String, maxLength:25, group:'/Listing/Compensation'},
  TransactionBrokerCompensation: {type:String, maxLength:25, group:'/Listing/Compensation'},
  TransactionBrokerCompensationType: {type:String, maxLength:25, group:'/Listing/Compensation'},
  DualVariableCompensationYN: {type:Boolean, group:'/Listing/Compensation'},
  LeaseRenewalCompensation: {type:String, maxLength:255, group:'/Listing/Compensation'},

  VOWEntireListingDisplayYN: {type:Boolean, group:'/Listing/Marketing'},
  VOWAddressDisplayYN: {type:Boolean, group:'/Listing/Marketing'},
  VOWConsumerCommentYN: {type:Boolean, group:'/Listing/Marketing'},
  VOWAutomatedValuationDisplayYN: {type:Boolean, group:'/Listing/Marketing'},
  SignOnPropertyYN: {type:Boolean, group:'/Listing/Marketing'},
  IDXEntireListingDisplayYN: {type:Boolean, group:'/Listing/Marketing'},
  IDXAddressDisplayYN: {type:Boolean, group:'/Listing/Marketing'},
  IDXConsumerCommentYN: {type:Boolean, group:'/Listing/Marketing'},
  IDXAutomatedValuationDisplayYN: {type:Boolean, group:'/Listing/Marketing'},
  PhotosCount: {type:Integer, default:0, group:'/Listing/Media'},
  PhotosChangeTimestamp: {type:Date, group:'/Listing/Media'},
  VideosCount: {type:Integer, group:'/Listing/Media'},
  VideosChangeTimestamp: {type:Date, group:'/Listing/Media'},
  DocumentsCount: {type:Integer, group:'/Listing/Media'},
  DocumentsChangeTimestamp: {type:Date, group:'/Listing/Media'},
  DocumentsAvailable: {type:String, maxLength:1024, group:'/Listing/Media'},
  VirtualTourURLUnbranded: {type:String, maxLength:8000, group:'/Listing/Marketing'},
  VirtualTourURLBranded: {type:String, maxLength:8000, group:'/Listing/Marketing'},
  PublicRemarks: {type:String, maxLength:4000, group:'/Listing/Remarks'},
  PrivateRemarks: {type:String, maxLength:4000, group:'/Listing/Remarks'},
  PrivateOfficeRemarks: {type:String, maxLength:4000, group:'/Listing/Remarks'},
  ShowingInstructions: {type:String, maxLength:4000, group:'/Listing/Showing'},
  ShowingContactPhoneNumber: {type:String, maxLength:16, group:'/Listing/Showing'},
  ShowingContactPhoneExtension: {type:Integer, group:'/Listing/Showing'},
  ShowingContactName: {type:String, maxLength:40, group:'/Listing/Showing'},
  ShowingContactType: {type:String, maxLength:75, group:'/Listing/Showing'},
  LockBoxLocation: {type:String, maxLength:255, group:'/Listing/Showing'},
  LockBoxType: {type:String, maxLength:255, group:'/Listing/Showing'},
  LockBoxSerialNumber: {type:String, maxLength:25, group:'/Listing/Showing'},
  Exclusions: {type:String, maxLength:1024, group:'/Listing/Contract'},
  Inclusions: {type:String, maxLength:1024, group:'/Listing/Contract'},
  Disclosures: {type:String, maxLength:4000, group:'/Listing/Contract'},
  Ownership: {type:String, maxLength:1024, group:'/Listing/Contract'},
  SpecialListingConditions: {type:String, maxLength:1024, group:'/Listing/Contract'},
  ListingTerms: {type:String, maxLength:1024, group:'/Listing/Contract'},
  ListingFinancing: {type:String, maxLength:1024, group:'/Listing/Contract'},
  BuyerFinancing: {type:String, maxLength:1024, group:'/Listing/Closing'},
  Contingency: {type:String, maxLength:1024, group:'/Listing/Closing'},
  Possession: {type:String, maxLength:255, group:'/Listing/Closing'},
  ClosingTerms: {type:String, maxLength:1024, group:'/Listing/Closing'},

  StreetNumber: {type:String, required:true, maxLength:25, group:'/Property/Location/Address'},
  StreetNumberNumeric: {type:Integer, group:'/Property/Location/Address'},
  StreetDirPrefix: {type:String, maxLength:15, group:'/Property/Location/Address'},
  StreetName: {type:String, required:true, maxLength:50, group:'/Property/Location/Address'},
  StreetAdditionalInfo: {type:String, maxLength:50, group:'/Property/Location/Address'},
  StreetSuffix: {type:String, maxLength:25, group:'/Property/Location/Address'},
  StreetSuffixModifier: {type:String, maxLength:25, group:'/Property/Location/Address'},
  StreetDirSuffix: {type:String, maxLength:15, group:'/Property/Location/Address'},
  UnitNumber: {type:String, maxLength:25, group:'/Property/Location/Address'},
  City: {type:String, required:true, maxLength:50, group:'/Property/Location/Address'},
  StateOrProvince: {type:String, required:true, maxLength:2, group:'/Property/Location/Address'},
  Country: {type:String, maxLength:2, default:'US', group:'/Property/Location/Address'},
  PostalCode: {type:String, required:true, maxLength:10, group:'/Property/Location/Address'},
  PostalCodePlus4: {type:String, maxLength:4, group:'/Property/Location/Address'},
  CarrierRoute: {type:String, maxLength:9, group:'/Property/Location/Address'},
  UnparsedAddress: {type:String, maxLength:255, group:'/Property/Location/Address'},
  PostalCity: {type:String, maxLength:50, group:'/Property/Location/Address'},
  CountyOrParish: {type:String, maxLength:50, group:'/Property/Location/Address'},
  Township: {type:String, maxLength:50, group:'/Property/Location/Address'},

  MLSAreaMajor: {type:String, maxLength:50, group:'/Property/Location/Area'},
  MLSAreaMinor: {type:String, maxLength:50, group:'/Property/Location/Area'},
  SubdivisionName: {type:String, maxLength:50, group:'/Property/Location/Area'},
  Latitude: {type:Number, group:'/Property/Location/GIS'},
  Longitude: {type:Number, group:'/Property/Location/GIS'},
  Directions: {type:String, maxLength:1024, group:'/Property/Location/GIS'},
  MapCoordinate: {type:String, maxLength:25, group:'/Property/Location/GIS'},
  MapCoordinateSource: {type:String, maxLength:25, group:'/Property/Location/GIS'},
  MapURL: {type:String, maxLength:8000, group:'/Property/Location/GIS'},

  CrossStreet: {type:String, maxLength:50, group:'/Property/Location/GIS'},
  ElementarySchool: {type:String, maxLength:50, group:'/Property/Location/School'},
  ElementarySchoolDistrict: {type:String, maxLength:50, group:'/Property/Location/School'},
  MiddleOrJuniorSchool: {type:String, maxLength:50, group:'/Property/Location/School'},
  MiddleOrJuniorSchoolDistrict: {type:String, maxLength:50, group:'/Property/Location/School'},
  HighSchool: {type:String, maxLength:50, group:'/Property/Location/School'},
  HighSchoolDistrict: {type:String, maxLength:50, group:'/Property/Location/School'},
  ListAgentNamePrefix: {type:String, maxLength:10, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentFirstName: {type:String, required:true, maxLength:50, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentMiddleName: {type:String, maxLength:50, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentLastName: {type:String, required:true, maxLength:50, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentNameSuffix: {type:String, maxLength:10, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentFullName: {type:String, maxLength:150, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentPreferredPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentPreferredPhoneExt: {type:Integer, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentCellPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentDirectPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentHomePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentPager: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentVoiceMail: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentVoiceMailExt: {type:Integer, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentTollFreePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentEmail: {type:String, required:true, maxLength:80, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentStateLicense: {type:String, maxLength:50, group:'/Listing/AgentOffice/ListAgent'},
  ListAgentDesignation: {type:String, maxLength:50, group:'/Listing/AgentOffice/ListAgent'},
  ListOfficeName: {type:String, required:true, maxLength:50, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficeFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficeEmail: {type:String, maxLength:80, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficeURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficeKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficeAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/ListOffice'},
  ListOfficeMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/ListOffice'},
  CoListAgentNamePrefix: {type:String, maxLength:10, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentFirstName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentMiddleName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentLastName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentNameSuffix: {type:String, maxLength:10, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentFullName: {type:String, maxLength:150, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentPreferredPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentPreferredPhoneExt: {type:Integer, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentCellPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentDirectPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentHomePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentPager: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentVoiceMail: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentVoiceMailExt: {type:Integer, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentTollFreePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentEmail: {type:String, maxLength:80, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentStateLicense: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListAgent'},
  CoListAgentDesignation: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListAgent'},
  CoListOfficeName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficeFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficeEmail: {type:String, maxLength:80, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficeURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficeKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficeAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoListOffice'},
  CoListOfficeMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/CoListOffice'},
  BuyerAgentNamePrefix: {type:String, maxLength:10, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentFirstName: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentMiddleName: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentLastName: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentNameSuffix: {type:String, maxLength:10, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentFullName: {type:String, maxLength:150, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentPreferredPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentPreferredPhoneExt: {type:Integer, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentCellPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentDirectPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentHomePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentPager: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentVoiceMail: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentVoiceMailExt: {type:Integer, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentTollFreePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentEmail: {type:String, maxLength:80, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentStateLicense: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerAgentDesignation: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerAgent'},
  BuyerOfficeName: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficeFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficeEmail: {type:String, maxLength:80, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficeURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficeKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficeAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/BuyerOffice'},
  BuyerOfficeMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/BuyerOffice'},
  CoBuyerAgentNamePrefix: {type:String, maxLength:10, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentFirstName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentMiddleName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentLastName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentNameSuffix: {type:String, maxLength:10, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentFullName: {type:String, maxLength:150, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentPreferredPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentPreferredPhoneExt: {type:Integer, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentCellPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentDirectPhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentHomePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentPager: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentVoiceMail: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentVoiceMailExt: {type:Integer, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentTollFreePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentEmail: {type:String, maxLength:80, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentStateLicense: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerAgentDesignation: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerAgent'},
  CoBuyerOfficeName: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficePhone: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficePhoneExt: {type:Integer, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficeFax: {type:String, maxLength:16, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficeEmail: {type:String, maxLength:80, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficeURL: {type:String, maxLength:8000, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficeKey: {type:String, maxLength:255, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficeAOR: {type:String, maxLength:50, group:'/Listing/AgentOffice/CoBuyerOffice'},
  CoBuyerOfficeMlsId: {type:String, maxLength:25, group:'/Listing/AgentOffice/CoBuyerOffice'},
  ListTeamDisplayName: {type:String, maxLength:50, group:'/Listing/AgentOffice/Team'},
  BuyerTeamDisplayName: {type:String, maxLength:50, group:'/Listing/AgentOffice/Team'},
  AssociationYN: {type:Boolean, group:'/Property/HOA'},
  AssociationName: {type:String, maxLength:50, group:'/Property/HOA'},
  AssociationPhone: {type:String, maxLength:16, group:'/Property/HOA'},
  AssociationFee: {type:Number, group:'/Property/HOA'},
  AssociationFeeFrequency: {type:String, maxLength:25, group:'/Property/HOA'},
  AssociationName2: {type:String, maxLength:50, group:'/Property/HOA'},
  AssociationPhone2: {type:String, maxLength:16, group:'/Property/HOA'},
  AssociationFee2: {type:Number, group:'/Property/HOA'},
  AssociationFee2Frequency: {type:String, maxLength:25, group:'/Property/HOA'},
  AssociationFeeIncludes: {type:String, maxLength:1024, group:'/Property/HOA'},
  AssociationAmenities: {type:String, maxLength:1024, group:'/Property/HOA'},
  LotSizeArea: {type:Number, group:'/Property/Characteristics'},
  LotSizeSource: {type:String, maxLength:50, group:'/Property/Characteristics'},
  LotSizeUnits: {type:String, maxLength:25, group:'/Property/Characteristics'},
  LotSizeDimensions: {type:String, maxLength:150, group:'/Property/Characteristics'},
  LotDimensionsSource: {type:String, maxLength:50, group:'/Property/Characteristics'},
  LotSizeAcres: {type:Number, group:'/Property/Characteristics'},
  LotSizeSquareFeet: {type:Number, group:'/Property/Characteristics'},
  FrontageType: {type:String, maxLength:50, group:'/Property/Characteristics'},
  FrontageLength: {type:String, maxLength:255, group:'/Property/Characteristics'},
  RoadFrontageType: {type:String, maxLength:255, group:'/Property/Characteristics'},
  RoadSurfaceType: {type:String, maxLength:255, group:'/Property/Characteristics'},
  RoadResponsibility: {type:String, maxLength:50, group:'/Property/Characteristics'},
  OccupantName: {type:String, maxLength:50, group:'/Property/OccupantOwner'},
  OccupantPhone: {type:String, maxLength:16, group:'/Property/OccupantOwner'},
  OccupantType: {type:String, maxLength:50, group:'/Property/OccupantOwner'},
  OwnerName: {type:String, maxLength:50, group:'/Property/OccupantOwner'},
  OwnerPhone: {type:String, maxLength:16, group:'/Property/OccupantOwner'},
  LeaseTerm: {type:String, maxLength:25, group:'/Property/Characteristics'},
  LandLeaseYN: {type:Boolean, group:'/Property/Characteristics'},
  LandLeaseAmount: {type:Number, group:'/Property/Characteristics'},
  LandLeaseAmountFrequency: {type:String, maxLength:25, group:'/Property/Characteristics'},
  LandLeaseExpirationDate: {type:Date, group:'/Property/Characteristics'},
  View: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  ViewYN: {type:Boolean, group:'/Property/Characteristics'},
  LotFeatures: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  CurrentUse: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  PossibleUse: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  DevelopmentStatus: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  NumberofLots: {type:Integer, group:'/Property/Characteristics'},
  HorseYN: {type:Boolean, group:'/Property/Characteristics'},
  HorseAmenities: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  CommunityFeatures: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  SeniorCommunityYN: {type:Boolean, group:'/Property/Characteristics'},
  PoolFeatures: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  PoolPrivateYN: {type:Boolean, group:'/Property/Characteristics'},
  SpaFeatures: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  SpaYN: {type:Boolean, group:'/Property/Characteristics'},
  WaterfrontYN: {type:Boolean, group:'/Property/Characteristics'},
  WaterBodyName: {type:String, maxLength:50, group:'/Property/Characteristics'},
  GrossScheduledIncome: {type:Number, group:'/Property/Financial'},
  IncomeIncludes: {type:String, maxLength:1024, group:'/Property/Financial'},
  OperatingExpense: {type:Number, group:'/Property/Financial'},
  OperatingExpenseIncludes: {type:String, maxLength:1024, group:'/Property/Financial'},
  NetOperatingIncome: {type:Number, group:'/Property/Financial'},
  CapRate: {type:Number, group:'/Property/Financial'},
  NumberOfUnitsLeased: {type:Integer, group:'/Property/Financial'},
  NumberOfUnitsMoMo: {type:Integer, group:'/Property/Financial'},
  NumberOfUnitsVacant: {type:Integer, group:'/Property/Financial'},
  ExistingLeaseType: {type:String, maxLength:75, group:'/Property/Financial'},
  UnitsFurnished: {type:String, maxLength:25, group:'/Property/Financial'},
  TotalActualRent: {type:Number, group:'/Property/Financial'},
  RentControlYN: {type:Boolean, group:'/Property/Financial'},
  NumberOfUnitsTotal: {type:Integer, group:'/Property/Characteristics'},
  NumberOfUnitsBuildings: {type:Integer, group:'/Property/Characteristics'},
  TenantPays: {type:String, maxLength:255, group:'/Property/Financial'},
  OwnerPays: {type:String, maxLength:255, group:'/Property/Financial'},
  VacancyAllowance: {type:Integer, group:'/Property/Financial'},
  CableTvExpense: {type:Number, group:'/Property/Financial'},
  ElectricExpense: {type:Number, group:'/Property/Financial'},
  GardnerExpense: {type:Number, group:'/Property/Financial'},
  FurnitureReplacementExpense: {type:Number, group:'/Property/Financial'},
  GasExpense: {type:Number, group:'/Property/Financial'},
  InsuranceExpense: {type:Number, group:'/Property/Financial'},
  OtherExpense: {type:Number, group:'/Property/Financial'},
  LicensesExpense: {type:Number, group:'/Property/Financial'},
  MaintenanceExpense: {type:Number, group:'/Property/Financial'},
  NewTaxesExpense: {type:Number, group:'/Property/Financial'},
  PestControlExpense: {type:Number, group:'/Property/Financial'},
  PoolExpense: {type:Number, group:'/Property/Financial'},
  SuppliesExpense: {type:Number, group:'/Property/Financial'},
  TrashExpense: {type:Number, group:'/Property/Financial'},
  WaterSewerExpense: {type:Number, group:'/Property/Financial'},
  WorkmansCompensationExpense: {type:Number, group:'/Property/Financial'},
  ProfessionalManagementExpense: {type:Number, group:'/Property/Financial'},
  ManagerExpense: {type:Number, group:'/Property/Financial'},
  FinancialDataSource: {type:String, maxLength:75, group:'/Property/Financial'},
  RentIncludes: {type:String, maxLength:255, group:'/Property/Financial'},
  Utilities: {type:String, maxLength:1024, group:'/Property/Utilities'},
  Electric: {type:String, maxLength:255, group:'/Property/Utilities'},
  Gas: {type:String, maxLength:255, group:'/Property/Utilities'},
  Telephone: {type:String, maxLength:255, group:'/Property/Utilities'},
  IrrigationWaterRightsYN: {type:Boolean, group:'/Property/Utilities'},
  IrrigationWaterRightsAcres: {type:Integer, group:'/Property/Utilities'},
  IrrigationSource: {type:String, maxLength:255, group:'/Property/Utilities'},
  WaterSource: {type:String, maxLength:1024, group:'/Property/Utilities'},
  DistanceToWater: {type:String, maxLength:255, group:'/Property/Utilities'},
  ElectricOnPropertyYN: {type:String, maxLength:1, group:'/Property/Utilities'},
  DistanceToElectric: {type:String, maxLength:255, group:'/Property/Utilities'},
  Sewer: {type:String, maxLength:1024, group:'/Property/Utilities'},
  DistanceToSewer: {type:String, maxLength:255, group:'/Property/Utilities'},
  DistanceToGas: {type:String, maxLength:255, group:'/Property/Utilities'},
  DistanceToPhoneService: {type:String, maxLength:255, group:'/Property/Utilities'},
  DistanceToStreet: {type:String, maxLength:255, group:'/Property/Utilities'},
  DistanceToSchools: {type:String, maxLength:255, group:'/Property/Utilities'},
  DistanceFromShopping: {type:String, maxLength:255, group:'/Property/Location'},
  DistanceToPlaceofWorship: {type:String, maxLength:255, group:'/Property/Location'},
  DistanceToBus: {type:String, maxLength:255, group:'/Property/Location'},
  DistanceToFreeway: {type:String, maxLength:255, group:'/Property/Location'},
  DistanceFromSchoolBus: {type:String, maxLength:255, group:'/Property/Location'},
  CropsIncludedYN: {type:Boolean, group:'/Property/Farming'},
  GrazingPermitsBlmYN: {type:Boolean, group:'/Property/Farming'},
  GrazingPermitsForestServiceYN: {type:Boolean, group:'/Property/Farming'},
  GrazingPermitsPrivateYN: {type:Boolean, group:'/Property/Farming'},
  CultivatedArea: {type:Number, group:'/Property/Farming'},
  PastureArea: {type:Number, group:'/Property/Farming'},
  RangeArea: {type:Number, group:'/Property/Farming'},
  WoodedArea: {type:Number, group:'/Property/Farming'},
  Vegetation: {type:String, maxLength:1024, group:'/Property/Farming'},
  Fencing: {type:String, maxLength:255, group:'/Property/Characteristics'},
  FarmCreditServiceInclYN: {type:Boolean, group:'/Property/Farming'},
  FarmLandAreaUnits: {type:String, maxLength:25, group:'/Property/Farming'},
  FarmLandAreaSource: {type:String, maxLength:50, group:'/Property/Farming'},
  BedroomsTotal: {type:Integer, default:0, group:'/Property/Structure'},
  BedroomsPossible: {type:Integer, group:'/Property/Structure'},
  BathroomsTotal: {type:String, default:0, maxLength:25, group:'/Property/Structure'},
  BathroomsFull: {type:Integer, group:'/Property/Structure'},
  BathroomsHalf: {type:Integer, group:'/Property/Structure'},
  BathroomsThreeQuarter: {type:Integer, group:'/Property/Structure'},
  BathroomsOneQuarter: {type:Integer, group:'/Property/Structure'},
  LivingArea: {type:Number, required:true, group:'/Property/Structure'},
  LivingAreaSource: {type:String, maxLength:50, group:'/Property/Structure'},
  LivingAreaUnits: {type:String, maxLength:25, group:'/Property/Structure'},
  AboveGradeFinishedArea: {type:Number, group:'/Property/Structure'},
  AboveGradeFinishedAreaSource: {type:String, maxLength:50, group:'/Property/Structure'},
  AboveGradeFinishedAreaUnits: {type:String, maxLength:25, group:'/Property/Structure'},
  BelowGradeFinishedArea: {type:Number, group:'/Property/Structure'},
  BelowGradeFinishedAreaSource: {type:String, maxLength:50, group:'/Property/Structure'},
  BelowGradeFinishedAreaUnits: {type:String, maxLength:25, group:'/Property/Structure'},
  BuildingAreaTotal: {type:Number, group:'/Property/Structure'},
  BuildingAreaSource: {type:String, maxLength:50, group:'/Property/Structure'},
  BuildingAreaUnits: {type:String, maxLength:25, group:'/Property/Structure'},
  CommonWalls: {type:String, maxLength:1024, group:'/Property/Structure'},
  PropertyAttachedYN: {type:Boolean, group:'/Property/Structure'},
  FoundationArea: {type:Number, group:'/Property/Structure'},
  GarageYN: {type:Boolean, group:'/Property/Structure'},
  GarageSpaces: {type:Number, group:'/Property/Structure'},
  AttachedGarageYN: {type:Boolean, group:'/Property/Structure'},
  CarportSpaces: {type:Number, group:'/Property/Structure'},
  CarportYN: {type:Boolean, group:'/Property/Structure'},
  OpenParkingYN: {type:Boolean, group:'/Property/Structure'},
  OpenParkingSpaces: {type:Number, group:'/Property/Structure'},
  CoveredSpaces: {type:Number, group:'/Property/Structure'},
  ParkingFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  OtherParking: {type:String, maxLength:1024, group:'/Property/Structure'},
  ParkingTotal: {type:Number, group:'/Property/Structure'},
  RVParkingDimensions: {type:String, maxLength:50, group:'/Property/Structure'},
  StoriesTotal: {type:Integer, group:'/Property/Structure'},
  Stories: {type:Integer, group:'/Property/Structure'},
  Levels: {type:String, maxLength:1024, group:'/Property/Structure'},
  EntryLocation: {type:String, maxLength:50, group:'/Property/Structure'},
  EntryLevel: {type:Integer, group:'/Property/Structure'},
  YearBuilt: {type:Integer, group:'/Property/Structure'},
  YearBuiltEffective: {type:Integer, group:'/Property/Structure'},
  YearBuiltDetails: {type:String, maxLength:1024, group:'/Property/Structure'},
  YearBuiltSource: {type:String, maxLength:60, group:'/Property/Structure'},
  NewConstructionYN: {type:Boolean, group:'/Property/Structure'},
  GreenBuildingVerification: {type:String, maxLength:1024, group:'/Property/Structure/Performance/GreenCertification'},
/* collection */
  Green: {type:"array", elementType:"reso.Green", group:'/Property/Structure/Performance/GreenCertification'},
/* collection */
  BuilderName: {type:String, maxLength:50, group:'/Property/Structure'},
  BuilderModel: {type:String, maxLength:50, group:'/Property/Structure'},
  Heating: {type:String, maxLength:1024, group:'/Property/Structure'},
  HeatingYN: {type:Boolean, group:'/Property/Structure'},
  Cooling: {type:String, maxLength:1024, group:'/Property/Structure'},
  CoolingYN: {type:Boolean, group:'/Property/Structure'},
  InteriorFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  ExteriorFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  PatioAndPorchFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  ArchitecturalStyle: {type:String, maxLength:1024, group:'/Property/Structure'},
  FireplaceFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  FireplacesTotal: {type:Integer, default:0, group:'/Property/Structure'},
  FireplaceYN: {type:Boolean, group:'/Property/Structure'},
  DoorFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  WindowFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  Roof: {type:String, maxLength:1024, group:'/Property/Structure'},
  ConstructionMaterials: {type:String, maxLength:1024, group:'/Property/Structure'},
  FoundationDetails: {type:String, maxLength:1024, group:'/Property/Structure'},
  Basement: {type:String, maxLength:1024, group:'/Property/Structure'},
  Flooring: {type:String, maxLength:1024, group:'/Property/Structure'},
  OtherStructures: {type:String, maxLength:1024, group:'/Property/Structure'},
  DirectionFaces: {type:String, maxLength:25, group:'/Property/Structure'},
  OtherEquipment: {type:String, maxLength:1024, group:'/Property/Equipment'},
  Appliances: {type:String, maxLength:1024, group:'/Property/Equipment'},
  LaundryFeatures: {type:String, maxLength:1024, group:'/Property/Characteristics'},
  SecurityFeatures: {type:String, maxLength:1024, group:'/Property/Equipment'},
  NumberOfSeparateElectricMeters: {type:Integer, group:'/Property/Utilities'},
  NumberOfSeparateGasMeters: {type:Integer, group:'/Property/Utilities'},
  NumberOfSeparateWaterMeters: {type:Integer, group:'/Property/Utilities'},
  GreenEnergyEfficient: {type:String, maxLength:1024, group:'/Property/Structure/Performance/GreenMarketing'},
  GreenEnergyGeneration: {type:String, maxLength:1024, group:'/Property/Structure/Performance/GreenMarketing'},
  GreenSustainability: {type:String, maxLength:1024, group:'/Property/Structure/Performance/GreenMarketing'},
  GreenWaterConservation: {type:String, maxLength:1024, group:'/Property/Structure/Performance/GreenMarketing'},
  GreenIndoorAirQuality: {type:String, maxLength:1024, group:'/Property/Structure/Performance/GreenMarketing'},
  GreenLocation: {type:String, maxLength:1024, group:'/Property/Structure/Performance/GreenMarketing'},
  WalkScore: {type:Integer, group:'/Property/Structure/Performance/GreenMarketing'},
  HabitableResidenceYN: {type:Boolean, group:'/Property/Structure'},
  MobileLength: {type:Integer, group:'/Property/Structure'},
  MobileWidth: {type:Integer, group:'/Property/Structure'},
  BodyType: {type:String, maxLength:1024, group:'/Property/Structure'},
  Skirt: {type:String, maxLength:1024, group:'/Property/Structure'},
  MobileDimUnits: {type:String, maxLength:25, group:'/Property/Structure'},
  ParkName: {type:String, maxLength:50, group:'/Property/Characteristics'},
  ParkManagerName: {type:String, maxLength:50, group:'/Property/Characteristics'},
  ParkManagerPhone: {type:String, maxLength:16, group:'/Property/Characteristics'},
  MobileHomeRemainsYN: {type:Boolean, group:'/Property/Characteristics'},
  Make: {type:String, maxLength:50, group:'/Property/Structure'},
  Model: {type:String, maxLength:50, group:'/Property/Structure'},
  NumberOfPads: {type:Integer, group:'/Property/Characteristics'},
  SerialU: {type:String, maxLength:25, group:'/Property/Structure'},
  DOH1: {type:String, maxLength:25, group:'/Property/Structure'},
  License1: {type:String, maxLength:25, group:'/Property/Structure'},
  SerialX: {type:String, maxLength:25, group:'/Property/Structure'},
  DOH2: {type:String, maxLength:25, group:'/Property/Structure'},
  License2: {type:String, maxLength:25, group:'/Property/Structure'},
  SerialXX: {type:String, maxLength:25, group:'/Property/Structure'},
  DOH3: {type:String, maxLength:25, group:'/Property/Structure'},
  License3: {type:String, maxLength:25, group:'/Property/Structure'},
  AccessibilityFeatures: {type:String, maxLength:1024, group:'/Property/Structure'},
  RoomsTotal: {type:Integer, group:'/Property/Structure/Rooms'},
  RoomType: {type:String, maxLength:1024, group:'/Property/Structure/Rooms'},
/* collection */
  Room: {type:"array", elementType:"reso.Room", group:'/Property/Structure/Rooms'},
/* collection */
/* collection */
  UnitType: {type:"array", elementType:"reso.UnitType", group:'/Property/UnitType'},
/* collection */
  Zoning: {type:String, maxLength:25, group:'/Property/Tax'},
  ZoningDescription: {type:String, maxLength:255, group:'/Property/Tax'},
  ParcelNumber: {type:String, maxLength:50, group:'/Property/Tax'},
  AdditionalParcelsYN: {type:Boolean, group:'/Property/Tax'},
  AdditionalParcelsDescription: {type:String, maxLength:255, group:'/Property/Tax'},
  TaxLot: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxBlock: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxTract: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxLegalDescription: {type:String, maxLength:6000, group:'/Property/Tax'},
  TaxAmount: {type:Integer, group:'/Property/Tax'},
  TaxAmountFrequency: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxYear: {type:Integer, group:'/Property/Tax'},
  TaxAssessedValue: {type:Integer, group:'/Property/Tax'},
  TaxExemptions: {type:String, maxLength:1024, group:'/Property/Tax'},
  TaxOtherAssessmentAmount: {type:Integer, group:'/Property/Tax'},
  TaxOtherAssessmentAmountFrequency: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxBookNumber: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxMapNumber: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxParcelLetter: {type:String, maxLength:25, group:'/Property/Tax'},
  TaxStatusCurrent: {type:String, maxLength:50, group:'/Property/Tax'},
  PublicSurveySection: {type:String, maxLength:20, group:'/Property/Tax'},
  PublicSurveyTownship: {type:String, maxLength:20, group:'/Property/Tax'},
  PublicSurveyRange: {type:String, maxLength:20, group:'/Property/Tax'},

  /* non-standard fields */

  Photos:{type:Array, default:[]},
  Coordinates:{type:Object}
};
